### ISSUE TITLE
[BUG] Recipient hears echo of themselves during phone call with headphones on

### ISSUE THREAD

**Issue by mikep-13** [TeamNexus/issues#1]
#### Description
One of my friends called me, and I had headphones w/ an in-line mic. I answered, and he tells me he hears an echo of himself. Before I ended the call, I asked if there was still an echo, and he said yes.

#### Device
Samsung Galaxy S6, SM-G920T

#### Used build
NexusOS, 25th June 2017

[logcat.txt](https://github.com/TeamNexus/issues/files/1110199/logcat.txt)
*Log is from Kernel Adiutor because apparently the bug report from the Nexus app isn't so good

[EDIT] Just in case
[NexusOS-2017-06-28_14-11-11.zip](https://github.com/TeamNexus/issues/files/1110216/NexusOS-2017-06-28_14-11-11.zip)

**Comment by Lukas0610** [comment]
Probably fixed by https://github.com/TeamNexus/android_device_samsung_zero-common/commit/ded9e5ec749a886e8b659087f5419220ff083e04
