### ISSUE TITLE
Fingerprint Problem

### ISSUE THREAD

**Issue by andreiculda03** [TeamNexus/issues#10]
***FINGERPRINT ISSUES***

When i installed latest RR 5.8.3 from this site,during the installation progress fingerprint sensor worked just fine.After 2-3 hours it started not to recognize my fingerprint from all my registred fingers! Please fix it! I will use this rom after this is fixed!
***Samsung Galaxy S6 SM-G920F***
*ROM*
ResurrectionRemix with build date 01.07.2017, 19:55:30 ; Version:7.1.2 (Patch 2017-06-05)

**Comment by Lukas0610** [comment]
Please tell us what it prints if you try to unlock it or if even nothing happens and append a proper bugreport, you can find that option in the "The Nexus" ROM-Control

**Comment by andreiculda03** [comment]
Where i can find The Nexus,ROM-Control in Resurrection Remix ROM?

**Comment by mikep-13** [comment]
In the app drawer... It's a round blue icon with a big n with a long shadow
