### ISSUE TITLE
Heating Up and Lagging in Games and apps

### ISSUE THREAD

**Issue by Reylian2000** [TeamNexus/issues#11]
#### Description
While I was Gaming I noticed the Phone lagged and was heating up alot while with stock rom it did not. this also happened while using apps it would freeze.

#### Device
Samsung Galaxy S6 SM-G920W8 Canadian

#### Used build
ResurrectionRemix 1st July 2017

**Comment by Lukas0610** [comment]
1. This is not TouchWiz
2. What games, how long did you play, did you have e.g. WiFi, mobile-data or Bluetooth activated, screen-brightness?
