### ISSUE TITLE
SElinux enforcing

### ISSUE THREAD

**Issue by Lucian72** [TeamNexus/issues#14]
Do you want add a permissive kernel or possibiliti forma change enforcing on permissive ? 

#### Description
SElinux don't change 

#### Device
Samsung Galaxy S6 SM-G920F, ...

#### Used build
NexusOS 1/07/17

**Comment by Lukas0610** [comment]
The kernel is already set to Permissive, but for a full SafetyNet-Compatibility (and possible compatibility with other apps which may require Enforcing), the kernel always shows Enforcing.

**Comment by Lucian72** [comment]
But how do i added a functionality Viper4android ?
Sorry for my English i'm a italian students 😅

**Comment by Lucian72** [comment]
Thank you very mutch
