### ISSUE TITLE
Fingerprint Reader scans when screen is turned off

### ISSUE THREAD

**Issue by fabsau** [TeamNexus/issues#15]
### Description
4 Fingerprints are set up. If you turn off the screen, the fingerprint reader deactivates only when device enters deep sleep! Which means you can unlock the device for some seconds/minutes after screen turned off or after pressing power button.
How to test:
1. Set up finger print
2. Press powerbutton
3. Try to use fingerprint reader, effect is even more noticable if you use a wrong finger

I hope this is a bug and not a feature, since on stock rom this does not occur

PS:
I would attach logcat but on lineage I dont have the nexus app, could you please provide the app as download? I would like to provide more bug reports since i experienced several soft reboots and camera problems (mostly on the nexusOS 14.07 build, lineage seems way more stable for me)
Thank you <3 
### Device
Samsung Galaxy S6 SM-G920F

### User Build
lineage-14.1-20170717, was also noticed on nexusOS 14.07

**Comment by Lukas0610** [comment]
LineageOS hasn't the option to disable Always-on-FP, NexusOS, you can find it in the "Fingerprint"-Section in the ROM-Control.

**Comment by fabsau** [comment]
Yes and No. The same issue would occur on nexusOS (build 14.07) even when the option was turned off in the Rom Control App. Don't know about the most recent build...
