### ISSUE TITLE
Problem with google account

### ISSUE THREAD

**Issue by ghost** [TeamNexus/issues#16]
#### Description
After I install nexusOS Abd after install nano gapps when i went to the setup wizard, he got stuck in looking for updates after I setup my wifi!, but if I choose to setup WiFi later and then I try to add my google account, i receive a maessafe saying that the phone can't Connecticut to google servers

#### Device
Samsung Galaxy S6 SM-G920F

#### Used build
NexusOS 22 of July, 2017

**Comment by HeavenVolkoff** [comment]
I also have the same problems with the NexusOS's 22/07/2017 build on a SM-G925I

**Comment by Lukas0610** [comment]
Bugreport? Logcat?
