### ISSUE TITLE
In-Call Audio Can hear, but cant be heard

### ISSUE THREAD

**Issue by Sm0k3r83** [TeamNexus/issues#17]
Description
I can hear people when calling or being called, but the other person can not hear me. It's like the mic is not working.

Device
Samsung Galaxy S6 Edge 925W8.

Used build
ResurrectionRemix 15th July 2017

**Comment by xxJava** [comment]
T Mobile and Canadian devices aren't fully supported as of yet. If you want to talk while on W8, you need to go on speaker phone.

I recently had the time to clone the projects etc. and I'll hopefully start working on finishing the fix for our model.

**Comment by BoopSnoot** [comment]
Description
The same problem as @Sm0k3r83 

Device
Samsung Galaxy S6 SM-920F

Used build
ResurrectionRemix 15.07.2017

**Comment by Lukas0610** [comment]
Bugreport? Logcat?
