### ISSUE TITLE
Bootloop Updating  Via Nexus App

### ISSUE THREAD

**Issue by Reylian2000** [TeamNexus/issues#19]
#### Steps for a proper issue
[ ] **Report issues only from latest build**
[ ] Create and append bugreport from the "The Nexus"-app
[ ] Proper title
[ ] Proper description

 Description:
I wanted to try and update my phone to the latest 27 of july via the ota nexus app feature and when the update flashed succesfully when my phone rebooted it got stuck in a bootloop. tho after flashed manually everything worked perfect.

Device:
Samsung Galaxy S6 SM-G920W8 Canadian

Used build:
NexusOS-zero-multitarget-2017-07-27_2228

**Comment by Lukas0610** [comment]
What about some recovery-logs?

**Comment by Reylian2000** [comment]
ok letme get them

**Comment by Lukas0610** [comment]
Logs missing, please open a new bug with them appended
