### ISSUE TITLE
[BUG] Phone freezes completely sometimes when downloading many clips at the same time in Firefox

### ISSUE THREAD

**Issue by Umeaboy** [TeamNexus/issues#21]
#### Steps for a proper issue
[ResurrectionRemix-2017-08-05_21-58-14.zip](https://github.com/TeamNexus/issues/files/1202639/ResurrectionRemix-2017-08-05_21-58-14.zip)

#### Description
Not all the time, but every now and then when I use either the stable Firefox or the Nightly version of it and download several clips from a website the phone freezes completely (even the seconds on the clock stops running) so the only thing I can do is force reboot the phone. After reboot Firefox and Nightly seems to forget the last clip I started to download before the phone froze.

#### Device
Samsung Galaxy S6 Edge SM-G925F, ...

#### Used build
ResurrectionRemix 29th July 2017, ...

**Comment by Lukas0610** [comment]
I tried to reproduce the problem and took a look at the logs. I wasn't able to find something in your logs neither I was able to reproduce it, maybe someone can reproduce it and send me some logs too

**Comment by Umeaboy** [comment]
And did you use a Samsung Galaxy S6 Edge to reproduce it? I think it's hardware dependent.
