### ISSUE TITLE
Unable to communicate with google servers 

### ISSUE THREAD

**Issue by Chronicrv** [TeamNexus/issues#22]
#### Description
[NexusOS-2017-08-06_18-46-20.zip](https://github.com/TeamNexus/issues/files/1203556/NexusOS-2017-08-06_18-46-20.zip)

Hey guys I've just flashed 

NEXUSOS (RELEASE) | 29.07.2017, 12:29:36 | 7.1.2 (Patch 2017-07-05)
 
and

Open Gapps arm64 7.1 Aroma build (installed everything)

and it works great except for that i cannot link my account (when i tried when just flashed it got stuck on looking for updates so i skipped that)

and now everytime i try and add my Google Account it goes to the Cheking info.. page and after a bit it says:
Coudln't sign in 

There was a problem communicating with Google Servers.

Tried: 

reflashing both packages
installing different opengapps packages (stock and such)
installing google play services separately

and someone in the xda post for the build mentioned to try and modify the Host file in /etc however when i tried to do it it said /system is read only 

Tried several methods to to remount it as RW but was unsuccessful.

tried this in adb incase you are intrested:
"mount -o remount,rw /system" 
also
"mount -o remount,rw rfc /system"

and non of them worked.

after 10+ of attempting different things I am now asking for assitance here 

#### Device
Samsung Galaxy S6 Edge SM-G925I

#### Used build
NEXUSOS 29.07.2017

**Comment by Lukas0610** [comment]
Please try with the newest build

**Comment by Chronicrv** [comment]
Hi, 


Same situation

[NexusOS-2017-08-06_18-46-20.zip](https://github.com/TeamNexus/issues/files/1205814/NexusOS-2017-08-06_18-46-20.zip)

Wiped

Data, System and cache and flashed:


NEXUSOS (TESTING) | 06.08.2017, 05:25:32 | 7.1.2 (Patch 2017-07-05)


but still not working

**Comment by Lukas0610** [comment]
Can you maybe create a new bugreport, having one from a fresh install would be very helpful

**Comment by Chronicrv** [comment]
Oh sorry I attached the wrong one.

[NexusOS-2017-08-07_15-44-40.zip](https://github.com/TeamNexus/issues/files/1206272/NexusOS-2017-08-07_15-44-40.zip)

**Comment by Chronicrv** [comment]
errmm the issue hasn't been resolved, any particular reason why it was closed?

**Comment by Chronicrv** [comment]
@Lukas0610 errmm the issue hasn't been resolved, any particular reason why it was closed?

**Comment by Lukas0610** [comment]
...

**Comment by Chronicrv** [comment]
I mean, i see the commit to fix the issue. I was jsut wondering if i should wait for another test/release build or is there something i can do to fix my current build 

Thank you for all your help!
