### ISSUE TITLE
Mirror screen on TVs

### ISSUE THREAD

**Issue by EnricoSignore** [TeamNexus/issues#24]
I can't connect my phone to any TV with screen mirroring. It says no devices avaible!

**Comment by Lukas0610** [comment]
Logs missing, take a Bugreport after you tried to connect to a TV several times.

**And please, remember that...**

**Comment by Usaamah99** [comment]
You also need to remember, if your relying on Samsung Services to work on AOSP then you shouldn't be on AOSP in the first place.
