### ISSUE TITLE
8.0 good work guys

### ISSUE THREAD

**Issue by Reylian2000** [TeamNexus/issues#27]
#### Steps for a proper issue
[ ] **Report issues only from latest build**
[ ] Create and append bugreport from the "The Nexus"-app
[ ] Proper title
[ ] Proper description

#### Description
ik we probably should not report buds like this to you because the 8.0 rom is new but apps dont install i just letting you know so you can add to bugs

#### Device
Samsung Galaxy S6 SM-G920F, ...

#### Used build
Android 8.0 build 1655 latest

**Comment by Lukas0610** [comment]
Android O is still a buggy OS, it's not surprising that some important things do nor work (System UI crashes on calls, Lockscreen may crash on wrong Login, Fingerprint may only work after a reboot)

Let's just be patient, wait some weeks and those bugs should be cleared
