### ISSUE TITLE
Graphics Glitches Android 8.0.0

### ISSUE THREAD

**Issue by mcamacho97** [TeamNexus/issues#29]
#### Description
The screen starts to blink and purple lines appear like a struttering, flickering, bad animation or glitches, I will add two images' links. I have this bug since the August 9th build Nougat from NexusTeam

https://drive.google.com/open?id=0B2SENILLEMgUSU83bWJoZGhpUWs
https://drive.google.com/open?id=0B2SENILLEMgUTV83cFFMajBRdGs

#### Device
Samsung Galaxy S6 SM-G920I

#### Used build
Lineage15 30th August 2017

**Comment by dhruv123456** [comment]
Same problem with lineage os 8.0.0 latest build ..sm g920i

**Comment by Lukas0610** [comment]
Fixed with https://github.com/TeamNexus/android_kernel_samsung_exynos7420/commit/202ed2e8a255132ea7971ecef830f5e649d37315
