### ISSUE TITLE
Bad performance, graphical glitches (Android 7.1.2)

### ISSUE THREAD

**Issue by Mrtenz** [TeamNexus/issues#31]
#### Description
I tried multiple builds of both NexusOS and Resurrection Remix, but all of them seem to have the same issue: bad performance and graphical glitches. Text has lines through it and does not render properly and it's flickering. Here is a picture of what it looks like:

![](http://g2f.nl/0765cl0)

Performance is also very bad. I have to wait multiple seconds after pressing something and the phone completely freezes after a couple of minutes.

I did a clean install before installing any of the builds.

#### Device
Samsung Galaxy S6 SM-G925F

#### Used build
Any of the Resurrection Remix and NexusOS builds currently available for Android 7.1.2.

**Comment by Lukas0610** [comment]
Fixed with https://github.com/TeamNexus/android_kernel_samsung_exynos7420/commit/0ce1d10305eeddcbe848a14a864d9afd487fe594
