### ISSUE TITLE
some apps like color switch are crashing on opening

### ISSUE THREAD

**Issue by qasim799** [TeamNexus/issues#34]
#### Steps for a proper issue
[ ] **Report issues only from latest build**
[ ] Create and append bugreport from the "The Nexus"-app
[ ] Proper title
[ ] Proper description

#### Description
While I opened color switch it got fc even it has all permissions allowed.

#### Device
Samsung Galaxy S6 SM-G925F, ...

#### Used build
lineage os 15 2nd september 2017, ...

**Comment by Lukas0610** [comment]
Fixed
