### ISSUE TITLE
Dual sim support

### ISSUE THREAD

**Issue by jinxul** [TeamNexus/issues#35]
#### Description
Secondary sim doesn't work.(primary sim seems to be working)

#### Device
Samsung Galaxy S6 SM-G920FD

#### Used build
LineageOS-15.0-zerofltexx-2017-09-02_2148

**Comment by Lukas0610** [comment]
Latest builds should have Dual-SIM support, please re-open this issue if it still doesn't work

**Comment by jinxul** [comment]
the issue still exists on latest build 9-12. the second sim doesn't work.

p.s: I can't reopen this issue since it's been closed by repo owner.

**Comment by Lukas0610** [comment]
Any logcat? If possible from startup on:
**BOTH** "adb logcat > logcat.txt" **and** "adb logcat -b radio > logcat.txt", reboot device and let it take logs for something like 2-3 minutes

**Comment by jinxul** [comment]
let me know if you need anything else:

[logcat_radio.txt](https://github.com/TeamNexus/issues/files/1303623/logcat_radio.txt)
[logcat_full.txt](https://github.com/TeamNexus/issues/files/1303624/logcat_full.txt)

**Comment by jinxul** [comment]
just tried the 9/14 build and issue still exists.

[914_logcat.txt](https://github.com/TeamNexus/issues/files/1305583/914_logcat.txt)
[914_radio.txt](https://github.com/TeamNexus/issues/files/1305584/914_radio.txt)

**Comment by Lukas0610** [comment]
Remount the system-partition and try to push that file to `/vendor/manifest.xml`: (**.xml, NOT .txt**, GitHub doesn't allow me to upload XML-files)
[manifest.txt](https://github.com/TeamNexus/issues/files/1305639/manifest.txt)

**Comment by jinxul** [comment]
nothing changed. 

[914_vendor_logcat.txt](https://github.com/TeamNexus/issues/files/1305683/914_vendor_logcat.txt)
[914_vendor_radio.txt](https://github.com/TeamNexus/issues/files/1305684/914_vendor_radio.txt)

**Comment by jinxul** [comment]
logs on the latest build (11/4)

[log.txt](https://github.com/TeamNexus/issues/files/1444152/log.txt)
[radio.txt](https://github.com/TeamNexus/issues/files/1444153/radio.txt)

**Comment by jinxul** [comment]
it seems to be fixed on 02/24 build.
