### ISSUE TITLE
No audio on Bluetooth calls Android 8 g920f

### ISSUE THREAD

**Issue by monelli97015** [TeamNexus/issues#37]
[btcallslog.txt](https://github.com/TeamNexus/issues/files/1278694/btcallslog.txt)

#### Description
While I was listening to music with my Bluetooth headphones, I received 2 voice calls. I replied, but I couldn't 
hear the caller through the bt headphones.
You can look at the end of the log to find the events

#### Device
Samsung Galaxy S6 SM-G920F, 

#### Used build
Android 8 Oreo Los 15 30/08 build.

**Comment by internetinnovations** [comment]
Confirmed /w Bluetooth calls in car.

**Device**
Samsung Galaxy S6 SM-G920F

**Used build**
8.0.0-20171104-2342
