### ISSUE TITLE
Bluetooth call audio doesn't work in the car

### ISSUE THREAD

**Issue by NikiSt96** [TeamNexus/issues#42]
**Description**
When I was connecting the phone to the bluetooth of the car for do the call, I noticed that the call did not work (for the rest it works), I installed the rom in the right way and flashed also the s6 edge kernel.

**Device**
Samsung Galaxy S6 Edge SM-G925F

**Used build**
LineageOS-8.0.0-zerofltexx-2017-09-17_1100

**Comment by karelwar** [comment]
I have the same problem 
device Samsung Galaxy S6 G920F
Build  LineageOS-8.0.0-2017-09-23-zerofltex
