### ISSUE TITLE
Kernel panic/oops - PhantomRom 8.0

### ISSUE THREAD

**Issue by Motorhead1991** [TeamNexus/issues#44]
While trying to port a new ROM to the Galaxy S6, I came across the need for hwbinder, so instead of updating the lineage kernel, I used your sources, but it won't boot.

Compiled with GCC 4.9 in the ROM source.

Galaxy S6 SM-G920I

**Comment by Lukas0610** [comment]
Having a last_kmsg would help me to understand the issue. Quickly guessing I'd say the device-tree isn't ready for O yet, but as I can't find an O one on your Account, I can't say more about the issue

**Comment by Motorhead1991** [comment]
I apologize for that, I've been out of the loop for almost two years and have to relearn some of the mannerisms :D. Anyways:

https://docs.google.com/document/d/15wEfbWyv_p3f09UkhycQlDaAFN4-8psozIo0YjPqa1A/edit?usp=sharing

**Comment by Motorhead1991** [comment]
Have I mentioned that I'm a bit rusty? LOL

I was using the prebuilt DTB still, which was poisoning the kernel I believe. Now my hangup is on the ROM side, with GLES_mali.

Thanks anyways though, especially for the quick response
