### ISSUE TITLE
Long Press Edge home button

### ISSUE THREAD

**Issue by sebasptsch** [TeamNexus/issues#45]
Recently, in the latest version of the UNOFFICIAL Lineage OS 8.0 I found that I am unable to launch google assistant via the home or "Ok Google" recognition

#### Device
Samsung Galaxy S6  Edge G925I

#### Used build
UNOFFICIAL Lineage OS 15 based on android 8.0

**Comment by sidharthmirch** [comment]
Have you looked at your settings and the keybind? It's usually set for Google Now but you can change it to Google Assistant

**Comment by sebasptsch** [comment]
in the default apps menu it is set to Enhanced Google Services. There are no other options. Long pressing the home button doesn't trigger _anything_ . Long press while in any app just triggers "go home" function.

**Comment by Stark003** [comment]
Long pressing the home button doesn't trigger _anything_

**Comment by sebasptsch** [comment]
@sidharthmirch which part of the settings is this in, Google Assistant settings or what?

**Comment by sidharthmirch** [comment]
sorry for the late reply, but you should have a menu called customizations, in there

**Comment by Pkhrl** [comment]
Long pressing home button doesn't response at all. Ok google is detecting fine when screen is on, and you can launch google assistant with the help of nova launcher.

**Comment by sebasptsch** [comment]
Must have been a problem with the gapps package...

**Comment by Pkhrl** [comment]
which gapps are you using? I'm using stock gapps

**Comment by sebasptsch** [comment]
Previously I have been using the provided gapps for the Android 8.0 on S6
edge rom
