### ISSUE TITLE
[Bug] Google Assistant headset microphone not working

### ISSUE THREAD

**Issue by kobutri** [TeamNexus/issues#5]
It seems as Google Assistant isn't detecting the microphone of my headset properly, while it also deactivates the internal microphone.
Talking to others I found out that I am not the only one experiencing
this problem. I also tried different models, so it is very unlikely to be related to
my headset. As it is working absolutely fine in the stock Samsung ROM the issue seems
to be related to the OS and not the App.
I was using a SM-G920F (Galaxy S6 flat international)
with the current build of NexusOS from 1st June.

**Comment by Lukas0610** [comment]
Please provide a bugreport, a good one would be taken right after you opened and tried Google Assistant

**Comment by kobutri** [comment]
sorry i thought i already appended it.
[NexusOS-2017-07-02_10-04-18.zip](https://github.com/TeamNexus/issues/files/1117674/NexusOS-2017-07-02_10-04-18.zip)
