### ISSUE TITLE
List of issue/bugs for current build

### ISSUE THREAD

**Issue by Pkhrl** [TeamNexus/issues#50]
#### Device
Samsung Galaxy S6 edge SM-G925i, ...
baseband version: g925idvu3fqc5
build number: zerofltexx-userdebug 8.0.0

#### Used build
Lineage 15, build 06-10-2017, Nexus rom

List of bugs that I'm facing:
-GPS: not working for navigation purpose, constantly asks to enable location.
-Mic: stops working when screen goes off while calling from stock google dialer . Works fine in viber, messenger...
-Camera: video recording changes screen orientation after finishing recording. Google Camera crashes frequently.
-Battery: I noticed heavy drain of battery comparing nougat. 
-Charging: Charging is working fine but doesn't goes charging icon on battery symbol when fully charged. If I charge which turning it off, it doesn't charges or may be just charging symbol not functioning, and yeah then when I try to switch on my phone , it doesn't response fast and takes ages to start. 

P.S. Thank you very much for developing this custom rom, it have got a really fast performance. Thanks again. Wish you could add further features as pixel devices, like "turn on wifi automatically" and "do not disturb mode: for driving(maps). 

Do I have to provide logcat?

**Comment by Pkhrl** [comment]
and yeah, -Long pressing home button doesn't trigger anything. 
                 - wifi automatically turns off when restarting device(Not always)

**Comment by Pkhrl** [comment]
[f.txt](https://github.com/TeamNexus/issues/files/1378823/f.txt)
[g.txt](https://github.com/TeamNexus/issues/files/1378824/g.txt)
[sm-g925i_logcat.txt](https://github.com/TeamNexus/issues/files/1378825/sm-g925i_logcat.txt)
[c.txt](https://github.com/TeamNexus/issues/files/1378826/c.txt)
[continued-logat.txt](https://github.com/TeamNexus/issues/files/1378827/continued-logat.txt)
[d.txt](https://github.com/TeamNexus/issues/files/1378828/d.txt)
[e.txt](https://github.com/TeamNexus/issues/files/1378829/e.txt)

NEW ISSUE: Couldn't even restart or turn on my device if I have plugged my charging cable, even I couldn't record my restart in adb, I mean when I restart while connecting cable, it just don't boot up. Sorry for too many logcat, as I was stuck in restarting my phone.Hope you will look at all the issues. Thank You @Lukas0610 @lucapolesel  @J0SH1X  @corewell  @lukasb06

**Comment by internetinnovations** [comment]
GPS issue confirmed. It's not working for navigation purpose, constantly asks to enable location. This makes Android Auto unusable, because the last step cannot be completed.

**Device**
Samsung Galaxy S6 SM-G920F

**Used build**
8.0.0-20171104-2342
