### ISSUE TITLE
Microphone bug

### ISSUE THREAD

**Issue by fedepuli** [TeamNexus/issues#52]
While I use mic, it doesn't work proprely. you hear many ailments, with frequent whistles and whistles.  I see this bug with whatsapp audio messages, whatsapp videocall, google duo videocall, normal 2g call. I also have to say that if i use headphones whit integrated mic, there are no problems... I guess the bug is just about internal mic. 

#### Device
Samsung Galaxy S6 SM-G920F

#### Used build
zerofltexx-user 8.0.0 OPR6.170623.012e0fce60267 test-keys

**Comment by BUCKFAE** [comment]
Same problem. Did you find any way to fix this?

**Comment by fedepuli** [comment]
Sorry man.. no way to solve this yet... I hope we could in the future with
new updates

Il 08 Nov 2017 22:25, "BUCKFAE" <notifications@github.com> ha scritto:

**Comment by BUCKFAE** [comment]
Ich think i can live with that...
Btw i could not figure out how to run my gear s2...? 

Thanks for your reply!
