### ISSUE TITLE
GPS Module Error

### ISSUE THREAD

**Issue by dylanbruinsma** [TeamNexus/issues#54]
Google maps and Pokemon Go cant seem to find my GPS signal, the installation went really smooth, but for some reason the mentioned apps cant seem to find the signal. I know Pokemon Go might seem a little dead, nut the GPS not working sounds like a bug to me.

#### Device
Samsung Galaxy S6 SM-G920F

#### Used build
2017-11-4_2342

**Comment by internetinnovations** [comment]
Here it's not even possible to log into PG. Infinite loading circle after choosing the Google account.

**Device**
Samsung Galaxy S6 SM-G920F

**Used build**
8.0.0-20171104-2342

**Comment by dylanbruinsma** [comment]
Do you use magisk or do you use SU?
With magisk correctly installed you hide your root status to PG

**Comment by internetinnovations** [comment]
SU, not magisk.

**Comment by dylanbruinsma** [comment]
Ash ok, SU won't hide your root. And to play PG you need to hide this. That's why I chose magisk, I highly recommend this. If you use SU for specific reasons then you should find something that hides your root.

**Comment by dylanbruinsma** [comment]
Aah*

**Comment by Lukas0610** [comment]
Fixed
