### ISSUE TITLE
Vulkan not actually supported / working (possibly driver related)

### ISSUE THREAD

**Issue by NarodGaming** [TeamNexus/issues#57]
#### Description
Simply put - you can't use Vulkan in the ROM, as the drivers aren't there, or there is some other underlying problem. Upon using an app that wants Vulkan (such as 3DMark) - it will tell you that it isnt supported. Apps such as DevCheck say its compatible, but another Vulkan related app says it finds "No Vulkan Compatible GPUS".

#### Device
Samsung Galaxy S6 SM-G920F

#### Used build
NexusOS 8.0.0 for Samsung Galaxy S6 (24th November build - latest as of posting)

**Comment by Lukas0610** [comment]
If you can link to tell me the apps which failed to recognize the Vulkan-capabilities, I could run them on an updated build

**Comment by NarodGaming** [comment]
https://play.google.com/store/apps/details?id=de.saschawillems.vulkancapsviewer
https://play.google.com/store/apps/details?id=com.futuremark.dmandroid.application

**Comment by Lukas0610** [comment]
Tested and confirmed to work with both applications
