### ISSUE TITLE
Device freezes upredictable

### ISSUE THREAD

**Issue by internetinnovations** [TeamNexus/issues#58]
#### Description
While the device was syncing general stuff, it crashed (freeze). This happened several times in upredictable moments. When rebooting by pressing standby and volume down, it shows the battery loading screen and crashes again. This can be reproduced. (Every time the device crashes it will crash again while pre-booting and starts again with the third try)

#### Device
Samsung Galaxy S6 SM-G920F

#### Used build
8.0.0-20171104-2342

**Comment by Lukas0610** [comment]
Unplug your phone before force-rebooting the device, so it directly goes to the default system again.

And the about the freezes: Not a single dev I wrote with has an idea on whats wrong here, so don't expect something in the next few weeks

**Comment by internetinnovations** [comment]
Thanks. I'll try that one.

I don't know if it's related to the freezes, but the lock screen sometimes shows a "unknown error string" at the bottom.

**Comment by internetinnovations** [comment]
The reboot issue has been solved by unplugging the phone before force-rebooting.

Freezing still occurs.
![whatsapp image 2017-12-04 at 13 10 05](https://user-images.githubusercontent.com/26227169/33552525-77373e24-d8f5-11e7-874e-e1b86ff567ae.jpeg)

**Comment by Lukas0610** [comment]
New kernel seems to finally fix this, I'm closing this for now to clean up, but I'm not promising anything
