### ISSUE TITLE
Audio & Video Playback Fix (Working, Fixed)

### ISSUE THREAD

**Issue by nickweberprojects** [TeamNexus/issues#61]
#### Description
The [libstagefrighthw.so](https://source.android.com/devices/media/) file which is the main file used by Android in order to make the Video & Audio Codec function, is not working. This problem occurred because the [libstagefrighthw.so](https://source.android.com/devices/media/) file didn't function proprely, it wasn't supported. Don't worry about this issue though, I've already found a fix. *Check end of article.*
#### Device
Samsung Galaxy S6 SM-G920F.

#### Used build
Latest (NexusOS 8.1.0 zerofltexx 2017-12-28 2113).

## Fix
To understand what the Media Codec looks like I highly recommend reading the small article [here](https://source.android.com/devices/media/).

Alright, so after some digging around I've finally found a replacement for the [libstagefrighthw.so](https://source.android.com/devices/media/) file that completely works. I've ran some tests and these are the results:

Works | Might Not Work
------------ | -------------
YouTube HD Playback (2K, 60fps) | Heavy Video Playback (4K, Not Sure)
Music Playback (Also Background) | 
Gallery Video Playback (Flawless) | 
Files Audio Playback (Flawless) | 

Conclusion, this works for 99,9% completely fine. I think this _**could**_ be a permanent fix.

**INSTRUCTIONS**
* Download the replacement **libstagefrighthw.so** file _(Download links below)_.
* Place the file in `/system/lib` **(it will ask to replace the old file).**
* Reboot the device.
* Done! Your video & audio playback should be working fine now.

**DOWNLOADS**

Link 1 (Google Drive): [Download](https://drive.google.com/open?id=1m_ZpPmoVg0BAbhgouJsLIfIZUxsPKYaD)
Link 2 (Mediafire): [Download](http://www.mediafire.com/file/x6bin8w41dlb12g/libstagefrighthw.so)
Link 3 (Files.fm): [Download](https://files.fm/u/hwtsdbp4)

_I hope this will work for everyone and that this will improve the further development of the rom, regards Nick Kylian Weber._

**Comment by Lukas0610** [comment]
Hey,

thanks for this issue. Just some more things I'm interested in:
 - Where did you take that file from, an Oreo-beta or somewhere different?
 - To be absolutely sure the working version is used, we'll need a 64-bit version too, not just 32-bit

And I also think it may fix 4K- and high-FPS-recording.

Again thanks

**Comment by nickweberprojects** [comment]
Hi Lukas,

Sorry for my late reaction. I just saw you closed my comment, what is the
reason for that? It's a working fix, the file is homemade by me and I allow
you to use it in all of your current and future projects. It is Oreo 8.0
and 8.1 compatible. It's coded universally which means that It's compatible
with 32bit, 64bit and x86 based devices.

Regards, Nick Weber.

!Note: In order for this fix to work you MUST clear cache and davlik after
replacing the codex!

Op 21 jan. 2018 11:54 schreef "Lukas Berger" <notifications@github.com>:

Closed #61 <https://github.com/TeamNexus/issues/issues/61>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/TeamNexus/issues/issues/61#event-1434013639>, or mute
the thread

**Comment by Lukas0610** [comment]
Hey,

the reason I closed this as invalid is that your libstagefrighthw simply prevents the HW-codecs from being loaded, and logcat confirms that in boot-phase (no sign of codecs being loaded) and on creation of a codec-instance (default Google SW-codecs are being created, no sign of our HW-codecs either).

Also, loading the codecs isn't the problem either. The problem seems to be in the "rendering"-area of the codec, as with 1.) without a shim makes the OMX-service crash at validating the buffer (an invalid buffer is being passed) and 2.) with a shim, it makes the service crash at locking the buffer.

From my current guess, we can only wait for official Samsung-codecs, and on XDA we already saw promising chats (especially one) with Samsung-reps.

**Comment by nickweberprojects** [comment]
Hi Lukas,

That's very weird, I've been using your rom for about 2 weeks now and ever
since I've replaced the lib I haven't had any problems with the audio and /
or video playbavk what so ever. I think this is getting quite interesting
now to be honest...

Regards, Nick.

Op 21 jan. 2018 12:42 schreef "Lukas Berger" <notifications@github.com>:

**Comment by Lukas0610** [comment]
Are you sure the codecs are even being loaded on your device?

**Comment by nickweberprojects** [comment]
Hi Lukas,

I might have found another possible fix for this problem. Flash both of
these files using TWRP on your device. The first one includes the Dobly
Audio Mod. The second one includes (what you need) the deep audio buffer
fix. I don't know if it is going to work because my audio and video do
already work fine so I won't really be able to tell a difference. But you
might be! ;)

Dobly Audio Mod:
http://forum.xda-developers.com/devdb/project/dl/?id=13950

Deep Buffer Fix:
http://forum.xda-developers.com/devdb/project/dl/?id=13100

Regards & succes, Nick.

NOTE: FLASH BOTH FILES! OR ELSE THIS CANNOT WORK!!!

Op 21 jan. 2018 12:42 schreef "Lukas Berger" <notifications@github.com>:

**Comment by nickweberprojects** [comment]
No, I'm not sure to be honest. But I'm sure that the playback works fine
though :).

Op 21 jan. 2018 12:53 p.m. schreef "Lukas Berger" <notifications@github.com
>:

Are you sure the codecs are even being loaded on your device?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/TeamNexus/issues/issues/61#issuecomment-359242760>, or mute
the thread
