### ISSUE TITLE
Screen stays black after standby

### ISSUE THREAD

**Issue by ghost** [TeamNexus/issues#62]
#### Steps for a proper issue
[ ] **Report issues only from latest build**
[ ] Create and append bugreport from the "The Nexus"-app
[ ] Proper title
[ ] Proper description

#### Description
Last two 8.1 and 8.0 builds for G925F have the same issue. The build installs fine and boots as well without problems.
As soon as the device goes into standby, i.e. switches the screen off, it is impossible to get the screen back on. It says black until a reboot (which has to be initiated using "adb reboot").

#### Device
Samsung Galaxy S6 Edge SM-G925F

#### Used build
https://files.nexus-roms.eu/Samsung/zero/8.1.0/2017-12-28/NexusOS-8.1.0-zerofltexx-2017-12-28_2113.zip

**Comment by Lukas0610** [comment]
Did you install the edge-kernel and were you able to gather logs?

**Comment by ghost** [comment]
Tried with and without kernel, this has been happening since these builds were changed to Oreo 8.0/8.1. I also use Advanced Wipe in TWRP to wipe all mount points, with and without OpenGapps.

Which log files? How can I get them?

**Comment by Lukas0610** [comment]
1.) The zeroltexx-Kernel is always required forSM-G925F/I
2.) "adb logcat -d > logcat.txt"

**Comment by ghost** [comment]
Thanks for the responses. It is working now. Initially when I tried with the kernel I loaded the kernel into the boot partition first and then used the image (which must be overwriting the boot partition with its own image).

Now I loaded the image, then the unofficial 8.1 opengapps and then only the kernel it did actually work.

Please close as resolved.
