### ISSUE TITLE
Netflix not work

### ISSUE THREAD

**Issue by Francesko90** [TeamNexus/issues#66]
Version: 2018-04-12
Model:  SM-G925F
Bootloader: G925FXXU5ERB1
Modem: G925FXXU5ERA5 

![image](https://user-images.githubusercontent.com/6740590/40575208-0825d224-60e1-11e8-8b17-d85fc5d61105.png)

Logcat: [logNetflix.txt](https://github.com/TeamNexus/issues/files/2041537/logNetflix.txt)

I installed app from apk mirror because on play store app is not compatible (with custom rom is it)

Thanks for your work

**Comment by PeterHindes** [comment]
You need a rom without root built in and you need to use magisk

**Comment by Lukas0610** [comment]
Fixed since some weeks in experimental builds
