### ISSUE TITLE
Battery drainage on RR

### ISSUE THREAD

**Issue by Mrtenz** [TeamNexus/issues#7]
#### Description
I switched from Lineage OS to Resurrection Remix and now my battery is draining very quickly. When the screen is on, I lose about 1% every 2 minutes. Even when brightness is set to the lowest value and power profile in TheNexus app is set to power save. I installed RR doing a clean install and restoring my apps using Titanium Backup.

I made some screenshots of BetterBatteryStats. I hope this helps to identify the problem. They can be found here: https://imgur.com/a/RA88e

If I need to provide more information, I'm happy to do so. Please tell me what information you need.

#### Device
Samsung Galaxy S6 Edge SM-G925F

#### Used build
Resurrection Remix, 1 July 2017

**Comment by Reylian2000** [comment]
same

**Comment by ghost** [comment]
Same

**Comment by Mrtenz** [comment]
Battery life has improved in the build of 15 July, but it is still not good.
