### ISSUE TITLE
teamnexus.github.io is showing pornography videos

### ISSUE THREAD

**Issue by dariotrombello** [TeamNexus/issues#71]
TeamNexus website is showing inappropiate content. 

https://teamnexus.github.io

![image](https://user-images.githubusercontent.com/24731809/56066412-f9814200-5d77-11e9-92aa-8ca5e9b2f40b.png)

**Comment by Lukas0610** [comment]
I unlinked nexus-roms.eu, which isn't owned by us anymore, from the github.io-page, so you shouldn't be redirected to that site anymore
